name 'dmon_agent'
maintainer 'Robert Cvitkovic'
maintainer_email 'robert.cvitkovic@xlab.si'
license 'all_rights'
description 'Installs/Configures dmon_agent'
long_description 'Installs/Configures dmon_agent'
version '0.1.0'

depends 'apt', '~> 2.9.1'
depends 'poise-python', '~>1.4.0'
