name 'dmon_agent'
maintainer 'Robert Cvitkovic'
maintainer_email 'robert.cvitkovic@xlab.si'
license 'all_rights'
description 'Installs/Configures dmon_agent'
long_description 'Installs/Configures dmon_agent'
version '0.1.2'

depends 'poise-archive'
depends 'poise-python'
