name 'dmon_agent'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dmon_agent'
long_description 'Installs/Configures dmon_agent'
version '0.1.0'
