name 'dmon'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dmon'
long_description 'Installs/Configures dmon'
version '0.1.0'

depends 'git', '~> 4.0.2'
depends 'poise-python', '~>1.4.0'
