name 'dmon'
maintainer 'Robert Cvitkovic'
maintainer_email 'robert.cvitkovic@xlab.si'
license 'all_rights'
description 'Installs/Configures dmon'
long_description 'Installs/Configures dmon'
version '0.1.1'

depends 'apt', '~> 2.9.1'
depends 'git', '~> 4.0.2'
depends 'poise-python', '~>1.4.0'
